### ISSUE TITLE
Match Strudel cpm and hydra bpm

### ISSUE THREAD

**Issue by atfornes** [atfornes/Hydra-strudel-extension#3]
When changing the rythm beats/cycles per minutes in strudel or hydra code, both should be updated and kept in synch.

**Comment by ojack** [comment]
Currently hydra's bpm only affects the speed of arrays used within hydra, wheras the cps updates the mini notation in both hydra and strudel. I think this behavior makes sense as is!

**Comment by atfornes** [comment]
> Currently hydra's bpm only affects the speed of arrays used within hydra, wheras the cps updates the mini notation in both hydra and strudel. I think this behavior makes sense as is!

Great! it makes sense. Closing this issue then :)
